# Generated by Django 3.2.3 on 2021-05-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('member_age', models.IntegerField(verbose_name='Возраст')),
                ('member_activity', models.CharField(max_length=200, verbose_name='Деятельность')),
            ],
        ),
    ]
