# Generated by Django 3.2.3 on 2021-05-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
